const ADD_TODO = "add todo"
const TOGGLE_TODO = "TOGGLE_TODO"
const DELETE_TODO = "DELETE_TODO"
const ADD_MOCK_TODO = "ADD_MOCK_TODO"


export {
    ADD_TODO,
    TOGGLE_TODO,
    DELETE_TODO,
    ADD_MOCK_TODO
}